LICENSE.md, Makefile, src/fs/zip-archives.ts
https://github.com/dinther/pathbuilder
https://github.com/jon-gilbert/openscad_attachable_text3d
=> Add pathbuilder & openscad_attachable_text3d

LICENSE.md, Makefile, src/fs/zip-archives.ts
https://github.com/BelfrySCAD/brailleSCAD
=> Add BelfrySCAD/brailleSCAD lib (LGPLv2.1)

LICENSE.md, Makefile, src/fs/zip-archives.ts
https://github.com/boltsparts/boltsparts (GPLv3)
https://github.com/AngeloNicoli/OpenSCAD-Snippet (MIT)
=> Add OpenSCAD-Snippet & boltsparts libs + some doc links for openscad & brailleSCAD

Makefile
Cf. discussion w/ @t-paul in https://github.com/openscad/openscad-playground/issues/2#issuecomment-2141787846
=> Always build w/ latest WASM snapshot

src/index.tsx, src/state/app-state.ts, src/state/fragment-state.ts, tsconfig.json
Makes the URL much shorter
https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream
https://caniuse.com/?search=compressionstream
=> compress state in url fragment w/ gzip now the APIs are standard

Makefile, src/fs/filesystem.ts, src/runner/actions.ts, src/runner/output-parser.ts, src/state/fragment-state.ts, tsconfig.json
Fixes https://github.com/openscad/openscad-playground/issues/32
Also, fix TS nits + don't skip NopSCADlib tests)
=> Fix relative imports

.gitignore, README.md, src/components/App.tsx, src/components/CustomizerPanel.tsx, src/components/HelpMenu.tsx, src/components/PanelSwitcher.tsx, src/runner/actions.ts, src/state/app-state.ts, src/state/customizer-types.ts, src/state/fragment-state.ts, src/state/model.ts
Already deployed at https://ochafik.com/openscad2/, extracted from https://github.com/openscad/openscad-playground/pull/37
=> add customizer

LICENSE.md, Makefile, examples/fonts.scad
Fixes https://github.com/openscad/openscad-playground/issues/21
=> Add Noto Fonts

LICENSE.md, Makefile, package.json, src/fs/zip-archives.ts
Added the [lasercut library](https://github.com/bmsleight/lasercut) by @bmsleight 
Also updated the bash path to `/usr/bin/env bash` to support systems such as NixOS
Please tell me if I did something wrong
=> Added Lasercut library

build-openscad-wasm.sh
https://www.shellcheck.net/wiki/SC2086
=> fix(wasm): prevent globbing and word splitting

build-openscad-wasm.sh
docker won't mount files outside home directory
=> fix build-openscad-wasm.sh

src/state/fragment-state.ts
Fixes https://github.com/openscad/openscad-playground/issues/63
=> Use history.replaceState instead of setting location.hash

src/components/ViewerPanel.tsx, src/state/default-scad.ts
Fixes https://github.com/openscad/openscad-playground/issues/53
=> Align orientation of model-viewer w/ OpenSCAD

src/io/export_glb.ts
Addresses some pathologically-unlit face cases (e.g. https://github.com/openscad/openscad-playground/issues/75 )
=> Tweak lighting of glb outputs

src/components/ViewerPanel.tsx, src/runner/actions.ts, src/runner/openscad-worker.ts, src/state/fragment-state.ts, tests/e2e.test.js
To prevent regressions such as https://github.com/openscad/openscad-playground/issues/80
=> Add library tests to e2e test

src/utils.ts, tests/e2e.test.js
Fixes https://github.com/openscad/openscad-playground/issues/82
=> Normalize CRLF to \n and test customizer in e2e test

src/runner/actions.ts
Fixes https://github.com/openscad/openscad-playground/issues/81
=> Preserve filename in output

package.json, src/language/openscad-editor-options.ts
Just one setting for the editor changed type.
=> chore(editor): update to latest version

jest-puppeteer.config.js, jest.config.js
cc/ @t-paul ([ref](https://github.com/openscad/openscad-playground/pull/116#issuecomment-2752025051))
=> Disable chrome sandbox on puppeteer test to fix CI

src/state/fragment-state.ts, src/state/initial-state.ts
=> Export to STL by default
